<?php

use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;

$user = Session::get('user');
Layout::includeLayout('header-login');

?>

<!-- container -->
<div class="container">
    <div id="caixa-estatisticas" class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <h2 class="text-center">Estatísticas</h2>
                <div class="row">
                    <div class="col-xs-4">
                        <span for="nome">Vintórias</span>
                    </div>
                    <div class="col-xs-4">
                        <span for="apelido">Derrotas</span>
                    </div>
                    <div class="col-xs-4">
                        <span for="data-nascimento">Jogos</span>
                    </div>
                </div>
    </div>
        <div id="caixa-dados-pessoais" class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <h2 class="text-center">Dados Pessoais</h2>
            <form action="<?=URL::toRoute('user/store')?>" method="post">
                <div class="row">
                    <div class="col-xs-6">
                        <label for="nome">Nome</label>
                        <input id="nome" name="primeironome" type="text" class="form-control" placeholder="Nome" value="<?= $user->primeironome?>" required>
                    </div>
                    <div class="col-xs-6">
                        <label for="apelido">Apelido</label>
                        <input id="apelido" name="apelido" type="text" class="form-control" placeholder="Apelido" value="<?= $user->apelido?>" required>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-6">
                        <label for="data-nascimento">Data de Nascimento</label>
                        <input type="date" name="datanascimento" id="data-nascimento" class="form-control" placeholder="DD/MM/AAAA" value="<?= $user->datanascimento?>" required>
                    </div>
                </div>
                <!--<div class="row">
                    <div class="col-xs-12">
                        <hr>
                    </div>
                </div>-->
                <div class="row">
                    <div class="col-xs-6">
                        <label for="email">Email</label>
                        <input id="email" name="email" type="email" class="form-control" placeholder="Email" value="<?= $user->email?>" required>
                    </div>
                    <div class="col-xs-6">
                        <label for="senha-login">Password</label>
                        <input id="senha-login" name="password" type="password" class="form-control" placeholder="Senha" value="<?= $user->password?>" required>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12 text-right">
                        <button class="btn btn" type="submit">Guardar Alterações</button>
                    </div>
                </div>
            </form>
        </div>

    </div>
</div> <!-- /container -->