<?php

use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;


Layout::includeLayout('header') ?>

<?php $user = Data::get('user')?>
<?php ErrMgr::attach($user) ?>

<!-- container -->
<div class="container">
    <div class="row">
        <div id="caixa-registo" class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <h2 class="text-center">REGISTO</h2>
            <form action="<?= URL::toRoute('user/store') ?>" method="post">
                <div class="row">
                    <div class="col-xs-6">
                        <label for="nome">Nome</label>
                        <input id="nome" name="primeironome" type="text" class="form-control" placeholder="Nome" value="<?=$user->primeironome?>" required>
                        <span><?= ErrMgr::bind('primeironome') ?></span>
                    </div>
                    <div class="col-xs-6">
                        <label for="apelido">Apelido</label>
                        <input id="apelido" name="apelido" type="text" class="form-control" placeholder="Apelido" value="<?=$user->apelido?>" required>
                        <span><?= ErrMgr::bind('apelido') ?></span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-6">
                        <label for="data-nascimento">Data de Nascimento</label>
                        <input type="date" name="datanascimento" id="data-nascimento" class="form-control" placeholder="DD/MM/AAAA" value="<?=$user->datanascimento?>" required>
                        <span><?= ErrMgr::bind('datanascimento') ?></span>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12">
                        <hr>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12">
                        <label for="email">Email</label>
                        <input id="email" name="email" type="email" class="form-control" placeholder="Email" value="<?=$user->email?>" required>
                        <span><?= ErrMgr::bind('email') ?></span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-6">
                        <label for="username-login">Username</label>
                        <input id="username-login" name="username" type="text" class="form-control" placeholder="Nome de Utilizador" value="<?=$user->username?>" required>
                        <span><?= ErrMgr::bind('username') ?></span>
                    </div>
                    <div class="col-xs-6">
                        <label for="senha-login">Password</label>
                        <input id="senha-login" name="password" type="password" class="form-control" placeholder="Senha" value="<?=$user->password?>" required>
                        <span><?= ErrMgr::bind('password') ?></span>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 text-right">
                            <button class="btn" type="submit">Registo</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>

    </div>
</div> <!-- /container -->

<?php Layout::includeLayout('footer') ?>