<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header-backoffice') ?>
<?php $users = Data::get('users') ?>


<!-- container -->
<div class="container" id="back-office">
    <div class="row">
        <h2 class="text-center">Lista de Jogadores</h2>
    </div>
    <div class="row">
        <div class="caixa-backoffice col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
            <table class="table">
                <thead>
                    <tr>
                        <th>Jogador</th>
                        <th class="text-right">Estado</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($users as $user) { ?>
                        <tr>
                            <td><span class="backoffice-player">(<?= $user->username ?>) <?= $user->email ?></span></td>
                            <td class="text-right">
                                <?php if($user->estado == 1): ?>
                                <a href="<?= Url::toRoute('user/block', $user->id)?>" style="color: #E12D2D;" role="button">Bloquear</a>
                                <?php else: ?>
                                    <a href="<?= Url::toRoute('user/block', $user->id)?>" style="color: #3FF018;" role="button">Desbloquear</a>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>

    </div>
</div> <!-- /container -->

<?php Layout::includeLayout('footer') ?>