<?php

use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;

Layout::includeLayout('header') ?>
<!--  $user = Data::get('user') ?>
 ErrMgr::attach('user') ?> -->

<!-- container -->
<div class="container">
	<div class="row">
		<div id="caixa-login" class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
			<h2 class="text-center">LOGIN</h2>
			<form action="<?= URL::toRoute('auth/login') ?>" method="post">
				<div>
					<label for="username-login">Username</label>
					<input id="username-login" name="username" type="text" class="form-control" placeholder="Nome de Utilizador"  required>
					<!-- <span> ErrMgr::bind('username') ?></span> -->
				</div>
				<div>
					<label for="senha-login">Password</label>
					<input id="senha-login" name="password" type="password" class="form-control" placeholder="Senha" required>
					<!-- <span> ErrMgr::bind('password') ?></span> -->
				</div>
				<div class="text-right">
					<button class="btn" type="submit">Login</button>
				</div>
				<hr>

				<div class="row text-center"> 
					<a href="<?= URL::toRoute('user/create')?>" class="link-registo">Não tens conta? Regista-te aqui!</a>
				</div>
			</form>
		</div>

	</div>
</div> <!-- /container -->

<?php Layout::includeLayout('footer') ?>