<?php

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header');
$scores = Data::get('scores');
$i = 1; ?>

<!-- container -->
<div class="container" id="topten">
    <div class="row">
        <h2 class="text-center">Top 10</h2>
    </div>
    <div class="row">
        <div id="caixa-topten" class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <table class="table">
                <thead>
                    <tr>
                        <th>Username</th>
                        <th class="text-right">Pontuação</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($scores as $score) : ?>
                        <?php if ($i <= 3) : ?>
                            <tr>
                                <td><?= $score->userid ?> <img src="<?= Asset::image('taca-' . $i . '.png') ?>" alt="taça" height="16"></td>
                                <td class="text-right"><?= $score->pontuacao ?></td>
                            </tr>
                            <?php $i++; ?>
                        <?php else : ?>
                            <tr>
                                <td><?= $score->userid ?></td>
                                <td class="text-right"><?= $score->pontuacao ?></td>
                            </tr>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </tbody>

            </table>
        </div>

    </div>
</div> <!-- /container -->

<?php Layout::includeLayout('footer') ?>