<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\URL;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport"    content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author"      content="Silvio Priem Mendes, PhD">

    <title>Weblogic MVC</title>

    <?=AssetBundler::css()?>

    <link rel="shortcut icon" href="<?= Asset::image('gt_favicon.png')?>">
    <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <!-- Custom styles for our site template -->
    <link rel="stylesheet" href="<?= Asset::css('/bootstrap-theme.css')?>" media="screen" >
    <link rel="stylesheet" href="<?= Asset::css('/mystyles.css') ?>" media="screen">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="<?= Asset::js('html5shiv.js')?>"></script>
    <script src="<?= Asset::js('respond.min.js')?>"></script>
    <![endif]-->
</head>

<body class="game">
<!-- Fixed navbar -->
<div class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <!-- Button for smallest screens -->
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
            <a class="navbar-brand" href="<?= URL::toRoute('home/index')?>"><img class="nav-logo-img" src="<?= Asset::image('logo.png')?>" alt="WEBlogic MVC"><span class="nav-logo-text">PARADICE</span></a>
        </div>
        <div class="navbar-collapse collapse text-center">
            <div class="players-box">
            <span class="span jogador1">
                Samuel
            </span>
            <span class="span vs">
                VS.
            </span>
            <span class="span jogador2">
                Computer
            </span>
            </div>
            
            <ul class="nav navbar-nav pull-right">
                <li><a href="<?= URL::toRoute('home/start')?>">Como Jogar?</a></li>
                <li><a id="header-btn-sair" class="btn" href="<?= URL::toRoute('home/logout')?>">Sair</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>