<?php

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;

$user = Session::get('user');
Layout::includeLayout('resultado-header');

$game = Session::get('game');
?>

<div id="tabuleiro-jogo">
    <div class="container">
        <div class="row">
            <div class="col-xs-2">
                <?php if ($game->tabuleiro->numerosBloqueadosP1->numBlock[1] == false) : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 1) ?>" class="caixa-numero text-center">
                        1
                    </a>
                <?php else : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 1) ?>" class="caixa-numero-bloqueado text-center">
                        1
                    </a>
                <?php endif; ?>
            </div>
            <div class="col-xs-8 text-center">
                <?php if ($game->tabuleiro->pontuacaoP1 < $game->tabuleiro->pontuacaoP2) : ?>
                    <h1 class="text-center" style="color: rgb(70, 230, 49);">Vitória</h1>
                <?php else : ?>
                    <h1 class="text-center" style="color: #E12D2D;">Derrota</h1>
                <?php endif; ?>
            </div>
            <div class="col-xs-2">
                <?php if ($game->tabuleiro->numerosBloqueadosP2->numBlock[1] == false) : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 1) ?>" class="caixa-numero-comp text-center">
                        1
                    </a>
                <?php else : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 1) ?>" class="caixa-numero-comp-bloqueado text-center">
                        1
                    </a>
                <?php endif; ?>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-2">
                <?php if ($game->tabuleiro->numerosBloqueadosP1->numBlock[2] == false) : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 2) ?>" class="caixa-numero text-center">
                        2
                    </a>
                <?php else : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 2) ?>" class="caixa-numero-bloqueado text-center">
                        2
                    </a>
                <?php endif; ?>
            </div>
            <div class="col-xs-4 text-center pontuacao-user">
                <span style="font-size: 50px;"><?= $game->tabuleiro->pontuacaoP1 ?></span>
            </div>
            <div class="col-xs-4 text-center pontuacao-comp">
                <span style="font-size: 50px;"><?= $game->tabuleiro->pontuacaoP2 ?></span>
            </div>
            <div class="col-xs-2">
                <?php if ($game->tabuleiro->numerosBloqueadosP2->numBlock[2] == false) : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 2) ?>" class="caixa-numero-comp text-center">
                        2
                    </a>
                <?php else : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 2) ?>" class="caixa-numero-comp-bloqueado text-center">
                        2
                    </a>
                <?php endif; ?>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-2">
                <?php if ($game->tabuleiro->numerosBloqueadosP1->numBlock[3] == false) : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 3) ?>" class="caixa-numero text-center">
                        3
                    </a>
                <?php else : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 3) ?>" class="caixa-numero-bloqueado text-center">
                        3
                    </a>
                <?php endif; ?>
            </div>
            <div class="col-xs-8">

            </div>
            <div class="col-xs-2">
                <?php if ($game->tabuleiro->numerosBloqueadosP2->numBlock[3] == false) : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 3) ?>" class="caixa-numero-comp text-center">
                        3
                    </a>
                <?php else : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 3) ?>" class="caixa-numero-comp-bloqueado text-center">
                        3
                    </a>
                <?php endif; ?>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-2">
                <?php if ($game->tabuleiro->numerosBloqueadosP1->numBlock[4] == false) : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 4) ?>" class="caixa-numero text-center">
                        4
                    </a>
                <?php else : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 4) ?>" class="caixa-numero-bloqueado text-center">
                        4
                    </a>
                <?php endif; ?>
            </div>
            <div class="col-xs-8">

            </div>
            <div class="col-xs-2">
                <?php if ($game->tabuleiro->numerosBloqueadosP2->numBlock[4] == false) : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 4) ?>" class="caixa-numero-comp text-center">
                        4
                    </a>
                <?php else : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 4) ?>" class="caixa-numero-comp-bloqueado text-center">
                        4
                    </a>
                <?php endif; ?>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-2">
                <?php if ($game->tabuleiro->numerosBloqueadosP1->numBlock[5] == false) : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 5) ?>" class="caixa-numero text-center">
                        5
                    </a>
                <?php else : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 5) ?>" class="caixa-numero-bloqueado text-center">
                        5
                    </a>
                <?php endif; ?>
            </div>
            <div class="col-xs-8">

            </div>
            <div class="col-xs-2">
                <?php if ($game->tabuleiro->numerosBloqueadosP2->numBlock[5] == false) : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 5) ?>" class="caixa-numero-comp text-center">
                        5
                    </a>
                <?php else : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 5) ?>" class="caixa-numero-comp-bloqueado text-center">
                        5
                    </a>
                <?php endif; ?>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-2">
                <?php if ($game->tabuleiro->numerosBloqueadosP1->numBlock[6] == false) : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 6) ?>" class="caixa-numero text-center">
                        6
                    </a>
                <?php else : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 6) ?>" class="caixa-numero-bloqueado text-center">
                        6
                    </a>
                <?php endif; ?>
            </div>
            <div class="col-xs-8">

            </div>
            <div class="col-xs-2">
                <?php if ($game->tabuleiro->numerosBloqueadosP2->numBlock[6] == false) : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 6) ?>" class="caixa-numero-comp text-center">
                        6
                    </a>
                <?php else : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 6) ?>" class="caixa-numero-comp-bloqueado text-center">
                        6
                    </a>
                <?php endif; ?>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-2">
                <?php if ($game->tabuleiro->numerosBloqueadosP1->numBlock[7] == false) : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 7) ?>" class="caixa-numero text-center">
                        7
                    </a>
                <?php else : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 7) ?>" class="caixa-numero-bloqueado text-center">
                        7
                    </a>
                <?php endif; ?>
            </div>
            <div class="col-xs-8">

            </div>
            <div class="col-xs-2">
                <?php if ($game->tabuleiro->numerosBloqueadosP2->numBlock[7] == false) : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 7) ?>" class="caixa-numero-comp text-center">
                        7
                    </a>
                <?php else : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 7) ?>" class="caixa-numero-comp-bloqueado text-center">
                        7
                    </a>
                <?php endif; ?>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-2">
                <?php if ($game->tabuleiro->numerosBloqueadosP1->numBlock[8] == false) : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 8) ?>" class="caixa-numero text-center">
                        8
                    </a>
                <?php else : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 8) ?>" class="caixa-numero-bloqueado text-center">
                        8
                    </a>
                <?php endif; ?>
            </div>
            <div class="col-xs-8 text-center">
                <div class="row">
                    <div class="col-xs-12">
                        <a href="<?= URL::toRoute('game/novoJogo') ?>" class="btn btn-novo-jogo">
                            Novo jogo
                        </a>
                        <a href="<?= URL::toRoute('game/sairJogo') ?>" class="btn btn-sair-jogo">
                            Sair
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-xs-2">
                <?php if ($game->tabuleiro->numerosBloqueadosP2->numBlock[8] == false) : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 8) ?>" class="caixa-numero-comp text-center">
                        8
                    </a>
                <?php else : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 8) ?>" class="caixa-numero-comp-bloqueado text-center">
                        8
                    </a>
                <?php endif; ?>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-2">
                <?php if ($game->tabuleiro->numerosBloqueadosP1->numBlock[9] == false) : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 9) ?>" class="caixa-numero text-center">
                        9
                    </a>
                <?php else : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 9) ?>" class="caixa-numero-bloqueado text-center">
                        9
                    </a>
                <?php endif; ?>
            </div>
            <div class="col-xs-8">

            </div>
            <div class="col-xs-2">
                <?php if ($game->tabuleiro->numerosBloqueadosP2->numBlock[9] == false) : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 9) ?>" class="caixa-numero-comp text-center">
                        9
                    </a>
                <?php else : ?>
                    <a href="<?= URL::toRoute('game/bloquearNumero', 9) ?>" class="caixa-numero-comp-bloqueado text-center">
                        9
                    </a>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>