<?php

use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('game-header') ?>
<?php 
    $user = Session::get('user');

    echo '<h1 style="color: #fff; padding-left: 20px;">User logado: ' . $user->username . '</h1>';
?>

<div id="tabuleiro-jogo">
    <div class="container">
        <div class="row">
            <div class="col-xs-2">
                <div class="caixa-numero text-center">
                    1
                </div>
            </div>
            <div class="col-xs-8 text-center">
                Pontuação
            </div>
            <div class="col-xs-2">
                <div class="caixa-numero-comp text-center">
                    1
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-2">
                <div class="caixa-numero text-center">
                    2
                </div>
            </div>
            <div class="col-xs-4 text-center pontuacao-user">
                22
            </div>
            <div class="col-xs-4 text-center pontuacao-comp">
                22
            </div>
            <div class="col-xs-2">
                <div class="caixa-numero-comp text-center">
                    2
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-2">
                <div class="caixa-numero text-center">
                    3
                </div>
            </div>
            <div class="col-xs-8">

            </div>
            <div class="col-xs-2">
                <div class="caixa-numero-comp text-center">
                    3
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-2">
                <div class="caixa-numero text-center">
                    4
                </div>
            </div>
            <div class="col-xs-8">

            </div>
            <div class="col-xs-2">
                <div class="caixa-numero-comp text-center">
                    4
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-2">
                <div class="caixa-numero text-center">
                    5
                </div>
            </div>
            <div class="col-xs-8">

            </div>
            <div class="col-xs-2">
                <div class="caixa-numero-comp text-center">
                    5
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-2">
                <div class="caixa-numero text-center">
                    6
                </div>
            </div>
            <div class="col-xs-8">

            </div>
            <div class="col-xs-2">
                <div class="caixa-numero-comp text-center">
                    6
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-2">
                <div class="caixa-numero text-center">
                    7
                </div>
            </div>
            <div class="col-xs-8">

            </div>
            <div class="col-xs-2">
                <div class="caixa-numero-comp text-center">
                    7
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-2">
                <div class="caixa-numero text-center">
                    8
                </div>
            </div>
            <div class="col-xs-8 text-center">
            <button class="btn btn-lancar-dados">lançar dados</button>
            </div>
            <div class="col-xs-2">
                <div class="caixa-numero-comp text-center">
                    8
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-2">
                <div class="caixa-numero text-center">
                    9
                </div>
            </div>
            <div class="col-xs-8">
                
            </div>
            <div class="col-xs-2">
                <div class="caixa-numero-comp text-center">
                    9
                </div>
            </div>
        </div>
    </div>
</div>