<?php

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>

<!-- container -->
<div class="container" id="topten">
    <div class="row">
        <h2 class="text-center">Top 10</h2>
    </div>
    <div class="row">
        <div id="caixa-topten" class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <table class="table">
                <thead>
                    <tr>
                        <th>Username</th>
                        <th class="text-right">Vitórias</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Player1 <img src="<?= Asset::image('taca-1.png')?>" alt="taça" height="16"></td>
                        <td class="text-right">10</td>
                    </tr>
                    <tr>
                        <td>Player1 <img src="<?= Asset::image('taca-2.png')?>" alt="taça" height="16"></td>
                        <td class="text-right">10</td>
                    </tr>
                    <tr>
                        <td>Player1 <img src="<?= Asset::image('taca-3.png')?>" alt="taça" height="16"></td>
                        <td class="text-right">10</td>
                    </tr>
                    <tr>
                        <td>Player1</td>
                        <td class="text-right">10</td>
                    </tr>
                    <tr>
                        <td>Player1</td>
                        <td class="text-right">10</td>
                    </tr>
                    <tr>
                        <td>Player1</td>
                        <td class="text-right">10</td>
                    </tr>
                    <tr>
                        <td>Player1</td>
                        <td class="text-right">10</td>
                    </tr>
                    <tr>
                        <td>Player1</td>
                        <td class="text-right">10</td>
                    </tr>
                    <tr>
                        <td>Player1</td>
                        <td class="text-right">10</td>
                    </tr>
                    <tr>
                        <td>Player1</td>
                        <td class="text-right">10</td>
                    </tr>
                </tbody>

            </table>
        </div>

    </div>
</div> <!-- /container -->

<?php Layout::includeLayout('footer') ?>